server:
  port: 5500
 
spring:
  application:
    name: survey-says

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PSWD}
    url: jdbc:postgresql://${DB_URL}:5432/${DB}
    username: ${DB_UNM}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: false
    

